import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
// import styles1 from '../styles/styles1.module.css'
// the file name should include the module.css at the end
// to apply this css we have to use styles1.classname  in anuy div 
// how to use it we must use it in tag 
// tage name =classname{and name used in css file}
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>blog page by juniad </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          hunting coder
        </h1>
        <p className={styles.description}>
          a blog for hunting coder by a hunting coder
        </p>
        <div className={styles.divcontainer}>
          <div className={styles.blog}>
            {/* /* here i hve to write the location wiht only the /  */}
              // this will redriect the componet to the next page
            <Link href="/Blogitems">
              <h2>Blogitems
              </h2>
              <p>dsajdhksajdhksajdh sa dadadadasd https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"</p>
            </Link>
          </div>

          <div className={styles.blog}>
            <h2>lore ajdshsakjdhsakjd asdjksahdkhsada
            </h2>
            <p>dsajdhksajdhksajdh sa dadadadasd https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"</p>
          </div>
          <div className={styles.blog}>
            <h2>lore ajdshsakjdhsakjd asdjksahdkhsada
            </h2>
            <p>dsajdhksajdhksajdh sa dadadadasd https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"</p>
          </div>

        </div>

      </main >

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div >
  )
}
